#!/usr/bin/env python3
"""Generate a kitty color theme from matugen's colors.json.

Reads the colors.json produced by wallpaper.sh and writes a kitty-compatible
theme file. Kitty can include this file and reload on SIGUSR1.

Usage:
    python3 gen_kitty_theme.py [/path/to/colors.json] [/path/to/output.conf]

Defaults:
    input:  ~/.config/quickshell/colors.json  (or the sibling of this script)
    output: ~/.config/kitty/theme.conf
"""

import json
import os
import signal
import subprocess
import sys


def find_colors_json():
    """Look for colors.json in common locations."""
    candidates = [
        os.path.expanduser("~/.config/quickshell/colors.json"),
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "colors.json"),
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "colors.json"),
    ]
    for p in candidates:
        if os.path.exists(p):
            return p
    return None


def get(colors, key, mode="dark"):
    """Safely extract a hex color from the matugen JSON."""
    try:
        return colors[key][mode]["color"]
    except (KeyError, TypeError):
        return None


def generate(input_path, output_path):
    with open(input_path) as f:
        data = json.load(f)

    c = data.get("colors", {})

    bg           = get(c, "background")       or "#101510"
    fg           = get(c, "on_background")    or "#e0e4db"
    surface      = get(c, "surface")          or bg
    on_surface   = get(c, "on_surface")       or fg
    muted        = get(c, "on_surface_variant") or "#9e9e9e"
    outline      = get(c, "outline")          or "#3a3a3a"
    primary      = get(c, "primary")          or "#c8b3fa"
    on_primary   = get(c, "on_primary")       or "#1e0a38"
    secondary    = get(c, "secondary")        or "#b8ccb5"
    tertiary     = get(c, "tertiary")         or "#a1ced6"
    error        = get(c, "error")            or "#ffb4ab"
    prim_cont    = get(c, "primary_container") or "#2d1f50"
    on_prim_cont = get(c, "on_primary_container") or "#e8deff"
    sec_cont     = get(c, "secondary_container") or "#3c4b39"
    tert_cont    = get(c, "tertiary_container") or "#1e4d52"
    surf_cont    = get(c, "surface_container") or "#1c1c1e"

    # Build a 16-color terminal palette derived from the Material You scheme.
    # We use the accent colors for the bright variants and desaturated versions
    # for the normal variants.
    theme = f"""# Auto-generated by gen_kitty_theme.py — do not edit manually
# This file is regenerated every time you change your wallpaper.

# ── Base colors ──────────────────────────────────────────────────────
background              {bg}
foreground              {fg}
selection_background    {primary}
selection_foreground    {on_primary}
cursor                  {primary}
cursor_text_color       {on_primary}
url_color               {tertiary}

# ── Window chrome ────────────────────────────────────────────────────
active_border_color     {primary}
inactive_border_color   {outline}
bell_border_color       {error}
active_tab_background   {prim_cont}
active_tab_foreground   {on_prim_cont}
inactive_tab_background {surf_cont}
inactive_tab_foreground {muted}
tab_bar_background      {bg}

# ── Terminal palette ─────────────────────────────────────────────────
# black
color0                  {bg}
color8                  {outline}

# red
color1                  {error}
color9                  {error}

# green
color2                  {primary}
color10                 {on_prim_cont}

# yellow
color3                  {secondary}
color11                 {on_prim_cont}

# blue
color4                  {tertiary}
color12                 {tertiary}

# magenta
color5                  {primary}
color13                 {on_prim_cont}

# cyan
color6                  {tertiary}
color14                 {tertiary}

# white
color7                  {muted}
color15                 {fg}
"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(theme)

    print(f"Kitty theme written to {output_path}")

    # Signal kitty to reload config
    try:
        result = subprocess.run(["pgrep", "-x", "kitty"], capture_output=True, text=True)
        for pid in result.stdout.strip().split("\n"):
            if pid:
                os.kill(int(pid), signal.SIGUSR1)
        print("Sent SIGUSR1 to kitty — theme reloaded live.")
    except Exception:
        pass  # kitty may not be running


if __name__ == "__main__":
    input_path = sys.argv[1] if len(sys.argv) > 1 else find_colors_json()
    output_path = sys.argv[2] if len(sys.argv) > 2 else os.path.expanduser("~/.config/kitty/theme.conf")

    if not input_path or not os.path.exists(input_path):
        print("Error: colors.json not found. Run wallpaper.sh first.", file=sys.stderr)
        sys.exit(1)

    generate(input_path, output_path)
