# ── Animations ────────────────────────────────────────────────────────────────
animations {
    enabled = true

    bezier = snappy,  0.23, 1.00, 0.32, 1.00
    bezier = linear,  0.00, 0.00, 1.00, 1.00

    animation = windows,        1, 3,  snappy, slide
    animation = windowsOut,     1, 3,  snappy, slide
    animation = windowsMove,    1, 3,  snappy
    animation = workspaces,     1, 4,  snappy, slidevert
    animation = fade,           1, 4,  linear
}
