# ── Startup ───────────────────────────────────────────────────────────────────
exec-once = qs                           # Start the shell
exec-once = swww-daemon                            # Start wallpaper daemon
exec-once = clipse -listen                         # Clipboard manager daemon
