# ── Startup ───────────────────────────────────────────────────────────────────
exec-once = qs                           # Start the shell
exec-once = awww-daemon                            # Start wallpaper daemon
exec-once = clipse -listen                         # Clipboard manager daemon
exec-once = gnome-keyring-daemon --start --components=pkcs11,secrets,ssh 
exec-once = systemctl --user start hyprpolkitagent
