# ═══════════════════════════════════════════════════════════════════════════════
#  H Y P R L A N D   C O N F I G
# ═══════════════════════════════════════════════════════════════════════════════

# Source modular configurations
source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/execs.conf
source = ~/.config/hypr/conf.d/general.conf
source = ~/.config/hypr/conf.d/decoration.conf
source = ~/.config/hypr/conf.d/animations.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/binds.conf
source = ~/.config/hypr/conf.d/rules.conf
bind = , Print, exec, qs -p /home/manpreet/dev/shell/.config/quickshell ipc call shell toggleScreenCapture
bind = SHIFT, Print, exec, qs -p /home/manpreet/dev/shell/.config/quickshell ipc call shell toggleScreenCapture
